parameters:
#    iag_home.example.class: Iag\HomeBundle\Example

services:
#    iag_home.example:
#        class: %iag_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
