parameters:
#    your_vendor_your.example.class: YourVendor\YourBundle\Example

services:
#    your_vendor_your.example:
#        class: %your_vendor_your.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
